name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Cache deps
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: go build -v
    - name: Build Cmd
      run: go build -v ./cmd/gitstrap
    - name: Test
      run: go test -v
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      env:
        GOROOT: ""
      with:
        args: "run"
